f = open("testfile.txt", 'r')
content = f.read()
f.close()
f = open("created_file.txt", 'w')
f.write(content)
f.close()
f = open("created_file.txt", 'r')
new_content = f.read()
print(new_content)
f.close()