file = open('me.txt','w', encoding="utf-8")
file.write("Krystian\n")
file.write("Gwizdala\n")
file.write("University of Ekonomics in Cracow\n")
file.write("Applied Informatics\n")
file.close()
file = open('me.txt','r')
content = file.read()
print(content)